---
- name: Configure and run prometheus container
  hosts: piservers
  become: true

  tasks:
    - name: Prometheus> Create prometheus.yml
      ansible.builtin.template:
        src: ../templates/prometheus.yml.j2
        dest: /home/{{ ansible_user }}/prometheus.yml

    - name: Prometheus> Pull Prometheus docker image
      community.docker.docker_image:
        name: "prom/prometheus"
        source: pull
        tag: "v2.45.6"
    
    - name: Prometheus> Run Prometheus container
      community.docker.docker_container:
        name: prometheus
        image: "prom/prometheus:v2.45.6"
        state: started
        restart_policy: always
        volumes:
          - "/home/{{ ansible_user }}/prometheus.yml:/etc/prometheus/prometheus.yml"
        network_mode: host
