---
- hosts: common
  become: true
  vars_files:
    - ../vars/vars.yml

  tasks:
    - name: SSH> Set authorized key taken from file
      ansible.posix.authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file', pub_ssh_key_path) }}"
      register: ssh_key_changed

    - name: SSH> Disallow SSH password authentication
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^PasswordAuthentication"
        line: "PasswordAuthentication no"
        state: present
        validate: sshd -t -f %s
      register: ssh_config_changed
    
    - name: SSH> Check if 50-cloud-init.conf exists
      stat:
        path: /etc/ssh/sshd_config.d/50-cloud-init.conf
      register: file_stat
    
    - name: SSH> Replace content in 50-cloud-init.conf
      replace:
        path: /etc/ssh/sshd_config.d/50-cloud-init.conf
        regexp: 'PasswordAuthentication yes'
        replace: 'PasswordAuthentication no'
      when: file_stat.stat.exists
      register: ssh_cloud_init_changed
    
    - name: SSH> Reboot to allow SSH changes to take effect
      reboot:
        reboot_timeout: 3600
      when: ssh_key_changed.changed or ssh_config_changed.changed or ssh_cloud_init_changed.changed
