---
- hosts: primary
  become: true
  vars:
    nexus_directory: "/home/{{ ansible_user }}/nexus"
    # NOTE(andrewpollack): Official image is only amd64, which won't work for the RaspPis.
    # Using community arm64 image instead, or can build via `nexus/Dockerfile`.
    nexus_image: "sonatypecommunity/nexus3:3.69.0"

  tasks:
    - name: Nexus> Create directory for Nexus
      file:
        path: "{{ nexus_directory }}"
        state: directory
        mode: '0755'
    
    - name: Nexus> Create writeable data directory for Nexus
      file:
        path: "{{ nexus_directory }}/data"
        state: directory
        mode: '0777'
    
    - name: Nexus> Create Nexus docker-compose.yml
      template:
        src: ../templates/nexus-docker-compose.yml.j2
        dest: "/home/{{ ansible_user }}/nexus/docker-compose.yml"
    
    - name: Nexus> Pull Nexus docker image
      community.docker.docker_image:
        name: "{{ nexus_image }}"
        source: pull
    
    - name: Nexus> Create systemd service file for Docker Compose
      copy:
        dest: /etc/systemd/system/nexus.service
        content: |
          [Unit]
          Description=Docker Compose application
          After=network.target

          [Service]
          Type=simple
          WorkingDirectory={{ nexus_directory }}
          ExecStart=/usr/bin/docker compose up
          ExecStop=/usr/bin/docker compose down
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Nexus> Reload systemd configuration
      command: systemctl daemon-reload

    - name: Nexus> Enable and start Docker Compose service
      systemd:
        name: nexus
        state: started
        enabled: yes
