---
- name: Configure and run prometheus container
  hosts: primary
  become: true
  vars:
    node_exporter_port: 9100
    prometheus_dir: "/home/{{ ansible_user }}/prometheus"

  tasks:
    - name: Prometheus> Gather common ansible_host variables
      set_fact:
        common_targets_with_node_exporter_port: "{{ groups['common'] | map('extract', hostvars, ['ansible_host']) | map('regex_replace', '(.+)', '\\1:{{ node_exporter_port }}') | list }}"
        common_inventory_names: "{{ groups['common'] }}"
      run_once: true

    - name: Prometheus> Create directory for Prometheus
      file:
        path: "{{ prometheus_dir }}"
        state: directory
        mode: '0755'

    - name: Prometheus> Create prometheus.yml
      ansible.builtin.template:
        src: ../templates/prometheus.yml.j2
        dest: "{{ prometheus_dir }}/prometheus.yml"
      register: prometheus_config

    - name: Prometheus> Pull Prometheus docker image
      community.docker.docker_image:
        name: "prom/prometheus"
        source: pull
        tag: "v2.45.6"
    
    - name: Prometheus> Run Prometheus container
      community.docker.docker_container:
        name: prometheus
        image: "prom/prometheus:v2.45.6"
        state: started
        restart_policy: always
        restart: "{{ prometheus_config.changed | default(false) }}"
        volumes:
          - "{{ prometheus_dir }}/prometheus.yml:/etc/prometheus/prometheus.yml"
        network_mode: host
