CREATE TABLE IF NOT EXISTS item (
    id SERIAL PRIMARY KEY,
    date_created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    date_modified TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    name VARCHAR(255) NOT NULL UNIQUE,
    aisle VARCHAR(255) NOT NULL
);
