name: Run npm lint

on:
  pull_request:

jobs:
  lint-npm:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: containers/meals-frontend/

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23.7.0'
          cache: 'npm'
          cache-dependency-path: 'containers/meals-frontend/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint
