name: Test recipe-maker

on:
  pull_request:
    paths:
      - 'containers/meals-go/**'

jobs:
  test-go:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: containers/meals-go/

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Install dependencies
        run: go get .
      - name: Test
        run: go test ./...
