name: Validate recipe-go

on:
  pull_request:

permissions:
  contents: read
    
jobs:
  test-go:
    runs-on: ubuntu-latest

    steps:
      # Just exit early for now, as this needs to be reworked for Bazel.
      - name: Exit early
        run: echo "Skipping tests for meals-go as they are not yet implemented."

  golangci:
    name: lint-go
    runs-on: ubuntu-latest
    
    steps:
      # Just exit early for now, as this needs to be reworked for Bazel.
      - name: Exit early
        run: echo "Skipping tests for meals-go as they are not yet implemented."
